name: Lootboxes
main: me.a8kj.lootbox.internal.plugin.LootboxPlugin
author: a8kj7sea
version: "0.3"
api-version: "1.13"
description: "A plugin that adds customizable lootboxes with various mechanics."
website: "https://github.com/a8kj7sea/Lootboxes"

commands:
  lootbox:
    description: "Main command for managing lootboxes."
